// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1sDIOchHmLP4DJi59OPgBg9PZ8r4wzgQ',
    appId: '1:93917365309:web:9d11289edfd4efd32d5654',
    messagingSenderId: '93917365309',
    projectId: 'w3covehousecleaning',
    authDomain: 'w3covehousecleaning.firebaseapp.com',
    storageBucket: 'w3covehousecleaning.appspot.com',
    measurementId: 'G-PGEFT27RNL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0E-m1ukZEOcma2u7pMKWjZxEYy-hjpys',
    appId: '1:93917365309:android:15ae69300ba778032d5654',
    messagingSenderId: '93917365309',
    projectId: 'w3covehousecleaning',
    storageBucket: 'w3covehousecleaning.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5yklkuUawnuIXv31HMk9uPTmfwYckTK8',
    appId: '1:93917365309:ios:fc9cd62027eb5d4b2d5654',
    messagingSenderId: '93917365309',
    projectId: 'w3covehousecleaning',
    storageBucket: 'w3covehousecleaning.appspot.com',
    iosClientId: '93917365309-qbifetobe1t1c3rsrpcqps9pjue8b3ji.apps.googleusercontent.com',
    iosBundleId: 'com.example.w3coveHousecleaning',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5yklkuUawnuIXv31HMk9uPTmfwYckTK8',
    appId: '1:93917365309:ios:fc9cd62027eb5d4b2d5654',
    messagingSenderId: '93917365309',
    projectId: 'w3covehousecleaning',
    storageBucket: 'w3covehousecleaning.appspot.com',
    iosClientId: '93917365309-qbifetobe1t1c3rsrpcqps9pjue8b3ji.apps.googleusercontent.com',
    iosBundleId: 'com.example.w3coveHousecleaning',
  );
}
